version: "3.8"

services:
  api:
    build: .
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./tests:/tests
    command: bash -c "wait-for-it -t 15 -s redis:6379 -- ./run.sh"

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"

  worker:
    build: .
    volumes:
      - ./src:/src
    env_file:
      - .env
    command: python log_listener.py
